name: Lint and Format

on:
  push:
    branches:
      - master # Cambia esto según la rama que quieras monitorear

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install package manager
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm i

      - name: Lint and Format
        run: |
          pnpm run lint 

      - name: Executing Tests
        run: |
          pnpm test

      # - name: Commit and Push Changes
      #   run: |
      #     git config --global user.email "kiu.manoguerra@gmail.com"
      #     git config --global user.name "lucas manoguerra"
      #     git add .
      #     git commit -m "Lint and Format code"
      #     git push -u origin/master

      

      - name: Complete
        run: echo "Linting and formatting with tests completed"
